# Tells k8s that the service account 'starexec-headnode' has the 'starexec-headnode-role' role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: starexec-headnode-rolebinding
subjects:
- kind: ServiceAccount
  name: starexec-headnode
  namespace: default
roleRef:
  kind: ClusterRole
  name: starexec-headnode-role
  apiGroup: rbac.authorization.k8s.io
