apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-stress-job-{{ jobNum }}
spec:
  template:
    metadata:
      labels:
        app: "cpu-stress-job"
    spec:
      nodeSelector:
        nodegroup: computenodes
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - "cpu-stress-job"
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: cpu-stress
        image: tptpstarexec/testingjoboverlap
        args:
          - "--timeout"
          - "{{ timeout }}"      # Stress CPU for 60 seconds
        resources:
          limits:
            cpu: "{{ cpuResourceReq }}"
          requests:
            cpu: "{{ cpuResourceReq }}"
      restartPolicy: Never
  backoffLimit: 4
