apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "starexec.fullname" . }}-config
  labels:
    {{- include "starexec.labels" . | nindent 4 }}
data:
  SSH_USERNAME: {{ .Values.starexecConfig.ssh.username | quote }}
  HOST_MACHINE: {{ .Values.starexecConfig.ssh.hostMachine | quote }}
  SSH_PORT: {{ .Values.starexecConfig.ssh.port | quote }}
  SSH_SOCKET_PATH: {{ .Values.starexecConfig.ssh.socketPath | quote }}
  # Add other configuration key-value pairs as needed
