{{- if .Values.persistence.volexport.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "starexec.fullname" . }}-volexport
  labels:
    {{- include "starexec.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.volexport.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.volexport.size | quote }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  {{- if .Values.persistence.volexport.volumeHandle }}
  # If using static provisioning with a pre-existing volume
  volumeName: {{ include "starexec.fullname" . }}-volexport-pv # Assumes a PV with this name exists
  {{- end }}
{{- end }}
