{{- if .Values.sshSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "starexec.sshSecretName" . }}
  labels:
    {{- include "starexec.labels" . | nindent 4 }}
type: Opaque
data:
  # Key name must match the subPath in the deployment volumeMount
  {{- if .Values.sshSecret.privateKey }}
  starexec_podman_key: {{ .Values.sshSecret.privateKey }}
  {{- else }}
  # Placeholder empty key for development environments
  starexec_podman_key: ""
  {{- end }}
{{- end }}
