{{- if and .Values.ingress.enabled .Values.ingress.createTlsSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "starexec.tlsSecretName" . }}
  labels:
    {{- include "starexec.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A base64 encoded TLS certificate (ingress.tlsCert) is required when ingress.createTlsSecret is true" .Values.ingress.tlsCert }}
  tls.key: {{ required "A base64 encoded TLS private key (ingress.tlsKey) is required when ingress.createTlsSecret is true" .Values.ingress.tlsKey }}
{{- end }}
