# ClusterRoleBinding to associate the 'starexec-headnode' service account with the 'starexec-headnode-role' role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: starexec-headnode-rolebinding
  labels:
    app: starexec
subjects:
  - kind: ServiceAccount
    name: starexec-headnode
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: starexec-headnode-role
