apiVersion: v1
kind: Service
metadata:
  name: starexec-service
spec:
  selector:
    app: starexec
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
