apiVersion: v1
kind: PersistentVolume
metadata:
  name: voldb-storage
  labels:
    volume: voldb
    type: local
    app: starexec
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /kubeStorage/vol1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volstar-storage
  labels:
    volume: volstar
    type: local
    app: starexec
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /kubeStorage/vol2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volpro-storage
  labels:
    volume: volpro
    type: local
    app: starexec
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /kubeStorage/vol3
  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: volexport-storage
  labels:
    volume: volexport
    type: local
    app: starexec
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /kubeStorage/vol4
