name: Infrastructure CI/CD

on:
  push:
    branches: [ master ]
    paths:
      - 'starexec-kubernetes/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'starexec-kubernetes/**'

env:
  WORKDIR: starexec-kubernetes

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Format Check
        run: |
          cd terraform
          terraform fmt -check
          
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
          
      - name: Terraform Validate
        run: |
          cd terraform
          terraform validate

  k8s-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Validate Kubernetes manifests
        run: |
          find microk8s/YAMLFiles -name "*.yaml" -exec kubectl apply --dry-run=client -f {} \;
          find terraform/YAMLFiles -name "*.yaml" -exec kubectl apply --dry-run=client -f {} \;